apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: hello-world

# buildMetadata: [managedByLabel, originAnnotations, transformerAnnotations]

images:
  - name: hello-world
    newTag: 1.23.3

labels:
  - pairs:
      environment: stage
      orchestrator: minikube
    includeTemplates: true

replicas:
- name: hello-world
  count: 1

resources:
- ../../base/

patchesStrategicMerge:
- configmap.yaml
- deployment.yaml
