apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: nginx

# buildMetadata: [managedByLabel, originAnnotations, transformerAnnotations]

images:
  - name: nginx
    newTag: latest

labels:
  - pairs:
      environment: local
      orchestrator: minikube
    includeTemplates: true

replicas:
- name: nginx
  count: 1

resources:
- deployment.yaml
- service.yaml
- configMap.yaml
